# Generated by Django 6.0.3 on 2026-03-19 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal_Types',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Type', models.TextField(db_column='Type')),
            ],
            options={
                'db_table': 'Animal_Types',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Type', models.TextField(db_column='Type')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Type', models.CharField(choices=[('Administrator', 'Administrator'), ('Warehouse_Operator', 'Warehouse_Operator')], db_column='Type', max_length=20)),
            ],
            options={
                'db_table': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(db_column='Full_Name', max_length=255)),
                ('Date_of_Birth', models.DateField(db_column='Date_of_Birth')),
                ('Phone_Number', models.CharField(db_column='Phone_Number', max_length=20)),
                ('Email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('Position_ID', models.ForeignKey(db_column='Position_ID', on_delete=django.db.models.deletion.RESTRICT, to='api.positions')),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Products_in_storage',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Name', models.CharField(db_column='Name', max_length=255)),
                ('Manufacturer', models.CharField(db_column='Manufacturer', max_length=255)),
                ('Expiry_Date', models.DateField(db_column='Expiry_Date')),
                ('Delivery_Date', models.DateField(db_column='Delivery_Date')),
                ('Status', models.CharField(choices=[('delivery', 'delivery'), ('exists', 'exists'), ('expired', 'expired'), ('deleted', 'deleted')], db_column='Status', default='exists', max_length=10)),
                ('Animal_Type_ID', models.ForeignKey(db_column='Animal_Type_ID', on_delete=django.db.models.deletion.RESTRICT, to='api.animal_types')),
                ('Category_ID', models.ForeignKey(db_column='Category_ID', on_delete=django.db.models.deletion.RESTRICT, to='api.categories')),
            ],
            options={
                'db_table': 'Products_in_storage',
            },
        ),
        migrations.CreateModel(
            name='Item_Movements',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Action', models.CharField(choices=[('disposal', 'disposal'), ('adding', 'adding')], db_column='Action', max_length=10)),
                ('Date_Time', models.DateTimeField(auto_now_add=True, db_column='Date_Time')),
                ('Description', models.TextField(null=True)),
                ('Employee_ID', models.ForeignKey(db_column='Employee_ID', on_delete=django.db.models.deletion.RESTRICT, to='api.employees')),
                ('Products_in_storage_ID', models.ForeignKey(db_column='Products_in_storage_ID', on_delete=django.db.models.deletion.CASCADE, to='api.products_in_storage')),
            ],
            options={
                'db_table': 'Item_Movements',
            },
        ),
        migrations.AddIndex(
            model_name='employees',
            index=models.Index(fields=['Position_ID'], name='idx_employees_position'),
        ),
        migrations.AddIndex(
            model_name='products_in_storage',
            index=models.Index(fields=['Category_ID'], name='idx_products_category'),
        ),
        migrations.AddIndex(
            model_name='products_in_storage',
            index=models.Index(fields=['Animal_Type_ID'], name='idx_products_animal'),
        ),
        migrations.AddIndex(
            model_name='products_in_storage',
            index=models.Index(fields=['Expiry_Date'], name='idx_products_expiry'),
        ),
        migrations.AddIndex(
            model_name='item_movements',
            index=models.Index(fields=['Date_Time'], name='idx_movements_date'),
        ),
        migrations.AddIndex(
            model_name='item_movements',
            index=models.Index(fields=['Products_in_storage_ID'], name='idx_movements_product'),
        ),
    ]
