# Generated by Django 6.0.3 on 2026-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_in_storage',
            name='Status',
            field=models.CharField(choices=[('exists', 'exists'), ('expired', 'expired'), ('deleted', 'deleted')], db_column='Status', default='exists', max_length=10),
        ),
    ]
