# Generated by Django 6.0.3 on 2026-03-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_in_storage_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal_Type',
            new_name='Animal_Types',
        ),
        migrations.AlterModelTable(
            name='animal_types',
            table='Animal_Types',
        ),
    ]
