# Generated by Django 6.0.3 on 2026-03-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_animal_type_animal_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_movements',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='products_in_storage',
            name='Quantity',
        ),
        migrations.AlterField(
            model_name='item_movements',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
